import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainForm extends JFrame {

  private JPanel mainPanel;
  private JButton collapseButton;
  private JPanel namePanel;
  private JPanel surname;
  private JPanel lastname;
  private JPanel nname;
  private JTextField textField1;
  private JLabel surnameLabel;
  private JTextField textField2;
  private JLabel nameLabel;
  private JTextField textField3;

  public static JFrame newFrame;

  public MainForm(String surname, String name, String lastName) {
    textField1.setText(surname);
    textField2.setText(name);
    textField3.setText(lastName);
  }

  public MainForm() {

    collapseButton.addActionListener(e -> {
        String surname = textField1.getText();
        String name = textField2.getText();
        String lastName = textField3.getText();
        if (surname.length() > 0 && name.length() > 0) {
          getCollapse(surname, name, lastName);
        } else {
          JOptionPane.showMessageDialog(
                  mainPanel,
                  "Поля: Фамилия (первое сверху) и Имя (второе сверху) не заполнены, их необходимо заполнить",
                  "Warning",
                  JOptionPane.PLAIN_MESSAGE
          );
        }
      });
  }

      private void getCollapse(String surname, String name, String lastName) {

        newFrame = new JFrame();

        Main.frame.setVisible(false);
        Main.frame.dispose();

        newFrame.setSize(600, 400);
        newFrame.setTitle("JFrame New Contact Form");

        newFrame.add(new AnotherForm(surname, name, lastName).getFullName());
        newFrame.add(new AnotherForm(surname, name, lastName).getPanel1());

        newFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        newFrame.setLocationRelativeTo(null);
        newFrame.setVisible(true);
      }


  public JPanel getMainPanel() {
    return mainPanel;
  }

  public JPanel getNamePanel() {
    return namePanel;
  }


  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new BorderLayout(7, 8));
    mainPanel.setOpaque(false);
    mainPanel.setPreferredSize(new Dimension(600, 400));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    panel1.setDoubleBuffered(false);
    panel1.setPreferredSize(new Dimension(140, 45));
    mainPanel.add(panel1, BorderLayout.SOUTH);
    panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-4517089)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    collapseButton = new JButton();
    collapseButton.setAutoscrolls(false);
    collapseButton.setContentAreaFilled(false);
    collapseButton.setPreferredSize(new Dimension(130, 35));
    collapseButton.setText("Collapse");
    panel1.add(collapseButton);
    namePanel = new JPanel();
    namePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    namePanel.setMinimumSize(new Dimension(600, 400));
    mainPanel.add(namePanel, BorderLayout.CENTER);
    surname = new JPanel();
    surname.setLayout(new GridBagLayout());
    surname.setPreferredSize(new Dimension(600, 100));
    surname.setToolTipText("Укажите фамилию");
    namePanel.add(surname);
    surname.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    textField1 = new JTextField();
    textField1.setAlignmentY(1.0f);
    textField1.setHorizontalAlignment(2);
    textField1.setPreferredSize(new Dimension(250, 30));
    textField1.setToolTipText("Укажите  фамилию");
    textField1.setVerifyInputWhenFocusTarget(false);
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    surname.add(textField1, gbc);
    surnameLabel = new JLabel();
    surnameLabel.setHorizontalAlignment(2);
    surnameLabel.setHorizontalTextPosition(0);
    surnameLabel.setPreferredSize(new Dimension(150, 30));
    surnameLabel.setText("Укажите  фамилию");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    surname.add(surnameLabel, gbc);
    nname = new JPanel();
    nname.setLayout(new GridBagLayout());
    nname.setPreferredSize(new Dimension(600, 100));
    nname.setToolTipText("Укажите имя");
    namePanel.add(nname);
    nname.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    textField2 = new JTextField();
    textField2.setHorizontalAlignment(2);
    textField2.setOpaque(false);
    textField2.setPreferredSize(new Dimension(250, 30));
    textField2.setToolTipText("Укажите  имя");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    nname.add(textField2, gbc);
    nameLabel = new JLabel();
    nameLabel.setPreferredSize(new Dimension(150, 30));
    nameLabel.setText("Укажите  имя");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    nname.add(nameLabel, gbc);
    lastname = new JPanel();
    lastname.setLayout(new GridBagLayout());
    lastname.setPreferredSize(new Dimension(600, 100));
    lastname.setToolTipText("Укажите отчество");
    namePanel.add(lastname);
    lastname.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    textField3 = new JTextField();
    textField3.setPreferredSize(new Dimension(250, 30));
    textField3.setToolTipText("Укажите  отчество");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    lastname.add(textField3, gbc);
    final JLabel label1 = new JLabel();
    label1.setPreferredSize(new Dimension(150, 30));
    label1.setText("Укажите  отчество");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    lastname.add(label1, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }

  private void createUIComponents() {
    // TODO: place custom component creation code here
  }
}
