import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeListener;

public class MainForm extends JFrame {

  private JPanel mainPanel;
  private JButton collapseButton;
  private JTextArea textArea1;
  private JTextArea textArea2;
  private JTextArea textArea3;
  private JPanel namePanel;

  public MainForm() {

    textArea1.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.BLACK, 2),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)));
    textArea2.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.BLACK, 2),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)));
    textArea3.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.BLACK, 2),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)));

    collapseButton.addActionListener(new Action() {
      @Override
      public Object getValue(String key) {
        return null;
      }

      @Override
      public void putValue(String key, Object value) {

      }

      @Override
      public void setEnabled(boolean b) {

      }

      @Override
      public boolean isEnabled() {
        return false;
      }

      @Override
      public void addPropertyChangeListener(PropertyChangeListener listener) {

      }

      @Override
      public void removePropertyChangeListener(PropertyChangeListener listener) {

      }

      @Override
      public void actionPerformed(ActionEvent e) {
        String surname = textArea1.getText();
        String name = textArea2.getText();
        if (surname.length() > 0 && name.length() > 0) {
          collapseButton.setText("Expand");
        }
        else {
          JOptionPane.showMessageDialog(
                  mainPanel,
                  "Поля: Фамилия (первое сверху) и Имя (второе сверху) не заполнены, их необходимо заполнить",
                  "Warning",
                  JOptionPane.PLAIN_MESSAGE
          );
        }

      }
    });


  }

  public JPanel getMainPanel() {
    return mainPanel;
  }

  public JPanel getNamePanel() {
    return namePanel;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new BorderLayout(7, 8));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    mainPanel.add(panel1, BorderLayout.SOUTH);
    collapseButton = new JButton();
    collapseButton.setAutoscrolls(false);
    collapseButton.setContentAreaFilled(false);
    collapseButton.setPreferredSize(new Dimension(130, 35));
    collapseButton.setText("Collapse");
    panel1.add(collapseButton);
    namePanel = new JPanel();
    namePanel.setLayout(new BorderLayout(0, 0));
    mainPanel.add(namePanel, BorderLayout.CENTER);
    textArea1 = new JTextArea();
    textArea1.setLineWrap(true);
    textArea1.setName("surname");
    textArea1.setPreferredSize(new Dimension(250, 100));
    textArea1.setRows(1);
    textArea1.setToolTipText("Укажите  фамилию");
    namePanel.add(textArea1, BorderLayout.NORTH);
    textArea2 = new JTextArea();
    textArea2.setLineWrap(true);
    textArea2.setName("name");
    textArea2.setPreferredSize(new Dimension(250, 100));
    textArea2.setRows(1);
    textArea2.setToolTipText("Укажите  имя");
    namePanel.add(textArea2, BorderLayout.CENTER);
    textArea3 = new JTextArea();
    textArea3.setLineWrap(true);
    textArea3.setMinimumSize(new Dimension(250, 10));
    textArea3.setName("lastName");
    textArea3.setPreferredSize(new Dimension(250, 100));
    textArea3.setRows(1);
    textArea3.setToolTipText("Укажите  отчество");
    namePanel.add(textArea3, BorderLayout.SOUTH);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }

}
