jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${ENCRYPTION_PASSWORD:secretKey}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?serverTimezone=Europe/Moscow
    username: root
    password: ENC(w7qYbKTj2l8T6ozrMwNQYpvJbVSQjUzG)


sites:
  url: http://www.playback.ru
  name: Магазин playback.ru