# example values

server:
port: 8080


jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${ENCRYPTION_PASSWORD:secretKey}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?serverTimezone=Europe/Moscow
    username: root
    password: ENC(w7qYbKTj2l8T6ozrMwNQYpvJbVSQjUzG)


jpa:
properties:
hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate:
  ddl-auto: update
  show-sql: true


indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
