# example values

server:
port: 8080

#
#jasypt:
#  encryptor:
#    algorithm: PBEWithMD5AndDES
#    password: ${ENCRYPTION_PASSWORD:secretKey}
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator


spring:
  datasource:
    username: root
    #password: ENC(w7qYbKTj2l8T6ozrMwNQYpvJbVSQjUzG)
    password: password
    url: jdbc:mysql://localhost:3306/web_search_engine?serverTimezone=Europe/Moscow
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://volochek.life/
      name: Volochek.life

