# example values

server:
  port: 8080

jwt:
  sessionTime: 120000000
  secret: secret_key

spring:
  datasource:
    username: root
    password: password
    #url: jdbc:mysql://localhost:3306/medical_service?serverTimezone=Europe/Moscow
    url: jdbc:mysql://localhost:3306/secure_fromDB?useSSL=false&serverTimezone=Europe/Moscow
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  main:
    allow-circular-references: true



